### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by dheimgartner** [dheimgartner/surveyjR#1]
- [x]  rename `id_container` -> `id` in `render_survey()` to match `survey_output()`
- [ ] add HTML / mardown rendering to package:

```{js}
// include: "https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"

var converter = new showdown.Converter();
survey
    .onTextMarkdown
    .add(function (survey, options) {
        //convert the markdown text to html
        var str = converter.makeHtml(options.text);
        //remove root paragraphs <p></p>
        str = str.substring(3);
        str = str.substring(0, str.length - 4);
        //set html
        options.html = str;
    });
```

- [ ] Write js function for getting particular value (by questionName) on the fly. This should be relatively easy. However, the survey object is initialized within the `renderSurvey()` js function and thus currently has no global scope. -> `survey.getValue("questionName")` and then `Shiny.setInputValue()` would be the idea... Probably best not to init survey in function call but simple script...
- [ ] Redirection after submit (f.ex. in `observeEvent()` where we collect the answers) -> either Shiny side or potentially adjust/extend `renderSurvey()`.
